# Generated by Django 4.0.5 on 2022-08-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_auxiliary_aux_alter_auxiliary1_aux1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='steps',
            field=models.TextField(max_length=1000, verbose_name='Steps'),
        ),
    ]
